version: '3.4'

networks:
  default:
    driver: bridge
services:
  api:
    build: ./backend
    networks:
      - default
    volumes:
      - ./backend/app/:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
    ports:
    - "5000:5000"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
    - "5432:5432"

  react:
    build: ./frontend
    networks:
      - default
    ports:
    - "3000:3000"
    environment:
      PORT: 3000
      PROXY_API: http://api:5000/
    depends_on:
      - api
  
  # keycloak:
  #     image: quay.io/keycloak/keycloak:15.0.2
  #     container_name: keycloak
  #     restart: always
  #     env_file:
  #       - .env
  #     # environment:
  #     #   - DB_VENDOR=POSTGRES
  #     #   - DB_ADDR=postgres
  #     #   - DB_PORT=5432
  #     #   - DB_SCHEMA=public
  #     #   - DB_DATABASE=dbesiee
  #     #   - DB_USER=userpd
  #     #   - DB_PASSWORD=postgrespassword
  #     #   - KEYCLOAK_USER=admin
  #     #   - KEYCLOAK_PASSWORD=admin
  #     ports:
  #     - "8080:8080"